const assert=require('node:assert/strict');
const {model,normalize,HOUR}=require('./core.js');
const e=(id,time,deaths=4)=>({id,timestamp:time*HOUR,deaths});
assert.equal(model([e('a',0)],0,1,10).height,.5);
assert.equal(model([e('a',0),e('b',0)],0,1,10).height,.25);
assert.equal(model([e('a',0),e('b',1)],HOUR,1,10).holdUntil,8*HOUR);
assert.equal(model([e('a',0)],6*HOUR,1,10).height,.7);
assert.equal(model([e('a',0),e('b',6)],6*HOUR,1,10).height,.35);
assert.equal(model([e('a',0)],100*HOUR,1,10).height,1);
assert.equal(model([e('a',2)],0,1,10).count,0);
assert.equal(model([],Date.now(),24,48).height,1);
assert.deepEqual(model([e('a',0),e('b',6)],7*HOUR,1,10),model([e('b',6),e('a',0)],7*HOUR,1,10));
const data={updated_at:'2026-09-15T00:00:00Z',incidents:[{id:1,date:'2026-09-01',city:'Example',state:'XX',victims:4,metaType:'mass_public_shooting',related_links:'javascript:alert(1) https://example.org'}]};
assert.equal(normalize(data).incidents.length,1);assert.deepEqual(normalize(data).incidents[0].links,['https://example.org']);
assert.throws(()=>normalize({...data,incidents:[...data.incidents,...data.incidents]}));
assert.throws(()=>normalize({...data,incidents:[{...data.incidents[0],victims:3}]}));
assert.throws(()=>normalize({...data,incidents:[{...data.incidents[0],metaType:'mass_killing'}]}));
const snapshot=normalize(require('./snapshot.json'));assert(snapshot.incidents.length>400);
console.log('PASS: cumulative lowering, additive holds, recovery, interrupted recovery, future dates, ordering, source filtering, validation, snapshot.');
